-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.41 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping data for table bctm_bdu.baocaosolieu: ~0 rows (approximately)
INSERT INTO `baocaosolieu` (`maBCSoLieu`, `tieuDeBaoCao`, `thoiGianGui`, `thoiGianDong`, `trangThai`, `maDonVi`) VALUES
	(2, 'Báo cáo dự trù HKIII', '2025-06-18 09:00:00', '2025-06-30 17:00:00', 'Chờ tiếp nhận', 2);

-- Dumping data for table bctm_bdu.chitietbaocao: ~0 rows (approximately)
INSERT INTO `chitietbaocao` (`maChiTiet`, `chiTiet`, `maBCSoLieu`) VALUES
(2, '{
"C1":{"H1":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":1},"H2":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":2},"H3":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":3},"H4":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":4},"H5":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":5},"H6":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":6},"H7":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":7},"H8":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":8},"H9":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":9},"H10":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":10},"H11":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":11},"H12":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":12},"H13":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":13},"H14":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":14},"H15":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":15},"H16":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":16},"H17":{"canLe":"center","kieuChu":["normal"],"giaTriNhap":17}},
"C2":{"H1":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phục vụ giảng dạy, học tập"},"H2":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Hoa hồng mở lớp (ngoài BDU)"},"H3":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Quảng cáo, tiếp thị"},"H4":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí hành chính"},"H5":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí văn phòng phẩm và đồ dùng văn phòng"},"H6":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí thuê, sửa chữa cơ sở vật chất"},"H7":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí tuyển sinh"},"H8":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí cho xe ô tô"},"H9":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi tài trợ"},"H10":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí liên kết đào tạo"},"H11":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí khai mở thị trường"},"H12":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi hoạt động sinh viên"},"H13":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi nghiên cứu khoa học"},"H14":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi bồi dưỡng nâng cao nghiệp vụ cho CBNV"},"H15":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí đào tạo không chuyên"},"H16":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí các hội đồng thi"},"H17":{"canLe":"left","kieuChu":["bold"],"giaTriNhap":"Chi phí khác"}},
"C3":{"H1":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H2":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H3":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":"Học kỳ"},"H4":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H5":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":"Học kỳ"},"H6":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":"Học kỳ"},"H7":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":"Học kỳ"},"H8":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H9":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H10":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H11":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":"Học kỳ"},"H12":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H13":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H14":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H15":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H16":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H17":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null}},
"C4":{"H1":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H2":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H3":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H4":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H5":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H6":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H7":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H8":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H9":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H10":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H11":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H12":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H13":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H14":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H15":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H16":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H17":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null}},
"C5":{"H1":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":170},"H2":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H3":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":1},"H4":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":3},"H5":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":1},"H6":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":1},"H7":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":1},"H8":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H9":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H10":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H11":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":1},"H12":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":32},"H13":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":2},"H14":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H15":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H16":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H17":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":1}},
"C6":{"H1":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":310000},"H2":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H3":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":2000000},"H4":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":15000000},"H5":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":3000000},"H6":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":5000000},"H7":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":3000000},"H8":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H9":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H10":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H11":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":10000000},"H12":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":25150000},"H13":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":20000000},"H14":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H15":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H16":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H17":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":10000000}},
"C7":{"H1":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":16200000,"CongThuc":"C5.H1 * C6.H1"},"H2":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H2 * C6.H2"},"H3":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":2000000,"CongThuc":"C5.H3 * C6.H3"},"H4":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":20000000,"CongThuc":"C5.H4 * C6.H4"},"H5":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":3000000,"CongThuc":"C5.H5 * C6.H5"},"H6":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":5000000,"CongThuc":"C5.H6 * C6.H6"},"H7":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":3000000,"CongThuc":"C5.H7 * C6.H7"},"H8":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H8 * C6.H8"},"H9":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H9 * C6.H9"},"H10":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H10 * C6.H10"},"H11":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":10000000,"CongThuc":"C5.H11 * C6.H11"},"H12":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":54500000,"CongThuc":"C5.H12 * C6.H12"},"H13":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":20000000,"CongThuc":"C5.H13 * C6.H13"},"H14":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H14 * C6.H14"},"H15":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H15 * C6.H15"},"H16":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null,"CongThuc":"C5.H16 * C6.H16"},"H17":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":10000000,"CongThuc":"C5.H17 * C6.H17"}},
"C8":{"H1":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H2":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H3":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H4":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H5":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H6":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H7":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H8":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H9":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H10":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H11":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H12":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H13":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H14":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H15":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H16":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null},"H17":{"canLe":"right","kieuChu":["normal"],"giaTriNhap":null}}
}', 2);
-- Dumping data for table bctm_bdu.thuoctinhbaocao: ~0 rows (approximately)
INSERT INTO `thuoctinhbaocao` (`maThuocTinh`, `chiTiet`, `maBCSoLieu`) VALUES
(2, '{
  "C1": {"Loai": "number", "DoRong": 80, "ChoPhepNhap": false, "TenThuocTinh": "STT"},
  "C2": {"Loai": "text", "DoRong": 300, "ChoPhepNhap": false, "TenThuocTinh": "Diễn giải"},
  "C3": {"Loai": "text", "DoRong": 100, "ChoPhepNhap": false, "TenThuocTinh": "ĐVT"},
  "C4": {"Loai": "text", "DoRong": 150, "ChoPhepNhap": false, "TenThuocTinh": "Cách tính"},
  "C5": {"Loai": "number", "DoRong": 100, "ChoPhepNhap": true, "TenThuocTinh": "Số lượng"},
  "C6": {"Loai": "number", "DoRong": 120, "ChoPhepNhap": true, "TenThuocTinh": "Đơn giá"},
  "C7": {"Loai": "number", "DoRong": 150, "ChoPhepNhap": false, "TenThuocTinh": "Thành tiền"},
  "C8": {"Loai": "text", "DoRong": 200, "ChoPhepNhap": true, "TenThuocTinh": "Ghi chú"}
}', 2)
/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
